from pathlib import Path
import sys
r=Path(sys.argv[1])
def rw(rel,fn):
 p=r/rel;s=p.read_text();n=fn(s);p.write_text(n)
def rep(s,a,b):
 if a not in s: raise SystemExit('missing: '+a[:80])
 return s.replace(a,b)
# model roles
rw('app/src/main/java/ru/printcheck/android/Models.java',lambda s: rep(rep(rep(s,'String url, label, article, sha256;','String url, label, article, sha256, role;'),'RemotePdf(String u, String l, String a){url=u;label=l;article=a;}','RemotePdf(String u, String l, String a, String r){url=u;label=l;article=a;role=r;}'),'String layoutFile, constructorFile, article;','String layoutFile, constructorFile, article, referenceType;'))
# strict read-only application PDF endpoint
p=r/'app/src/main/java/ru/printcheck/android/Safety.java';s=p.read_text();s=rep(s,'if(file&&!(u.getPath().toLowerCase(Locale.ROOT).endsWith(".pdf")||u.getPath().equals("/cart/act/mda")))throw new IllegalArgumentException("Это не ссылка на PDF-макет или конструктор");','''if(file){\n   String path=u.getPath();\n   boolean directPdf=path.toLowerCase(Locale.ROOT).endsWith(".pdf");\n   boolean uploadedMaket=path.equals("/cart/act/mda");\n   boolean applicationTemplate=false;\n   if(path.equals("/drawing")){\n    Map<String,String> qp=new HashMap<>();\n    if(q!=null)for(String pair:q.split("&")){String[] kv=pair.split("=",2);String k=URLDecoder.decode(kv[0],"UTF-8");String v=kv.length>1?URLDecoder.decode(kv[1],"UTF-8"):"";qp.put(k,v);}\n    applicationTemplate=qp.size()==2&&"getOrderItemPdf".equals(qp.get("action"))&&qp.getOrDefault("orderitemid","").matches("\\\\d{1,20}");\n   }\n   if(!(directPdf||uploadedMaket||applicationTemplate))throw new IllegalArgumentException("Это не разрешённая read-only ссылка на PDF");\n  }''');p.write_text(s)
# reference role in matching output
rw('app/src/main/java/ru/printcheck/android/RasterMatcher.java',lambda s:rep(s,'o.layoutFile=layout.file==null?layout.label:layout.file.getName();o.constructorFile=cons.file==null?cons.label:cons.file.getName();o.article=cons.article;o.layoutPage=lp.page;o.constructorPage=cp.page;','o.layoutFile=layout.file==null?layout.label:layout.file.getName();o.constructorFile=cons.file==null?cons.label:cons.file.getName();o.article=cons.article;o.referenceType=cons.role;o.layoutPage=lp.page;o.constructorPage=cp.page;'))
# MainActivity core
p=r/'app/src/main/java/ru/printcheck/android/MainActivity.java';s=p.read_text()
s=rep(s,'ArrayList<Models.RemotePdf> layouts=parse(root.getJSONArray("layouts"),false),templates=parse(root.getJSONArray("constructors"),true),applicationTemplates=parse(root.optJSONArray("applicationTemplates"),true);','ArrayList<Models.RemotePdf> layouts=parse(root.getJSONArray("layouts"),"layout"),templates=parse(root.getJSONArray("constructors"),"constructor"),applicationTemplates=parse(root.optJSONArray("applicationTemplates"),"application");')
a='''   ArrayList<Models.RemotePdf> all=new ArrayList<>(layouts);all.addAll(templates);all.addAll(applicationTemplates);int i=0;\n   for(Models.RemotePdf p:all){ensure();update("Скачиваю "+(++i)+" / "+all.size()+": "+p.label,10+i*25/all.size());download(p);}\n   ArrayList<Models.PdfIndex> li=new ArrayList<>(),ci=new ArrayList<>();\n   // One DPI for the entire order; never resize layout and constructor independently.\n   int dpi=RasterPdfIndexer.commonDpi(all);trace(new JSONObject().put("event","index").put("dpi",dpi));\n   for(Models.RemotePdf p:layouts){ensure();li.add(RasterPdfIndexer.index(p,dpi,s->update(s,40)));}\n   for(Models.RemotePdf p:templates){ensure();ci.add(RasterPdfIndexer.index(p,dpi,s->update(s,45)));}\n   ArrayList<Models.Occurrence> found=new ArrayList<>();int cmp=0,total=0;\n   for(Models.PdfIndex l:li)for(Models.PdfIndex c:ci)if(!l.pdf.itemIds.isEmpty()&&!c.pdf.itemIds.isEmpty()&&!Collections.disjoint(l.pdf.itemIds,c.pdf.itemIds))total++;\n   for(Models.PdfIndex l:li)for(Models.PdfIndex c:ci){ensure();if(l.pdf.itemIds.isEmpty()||c.pdf.itemIds.isEmpty()||!Collections.disjoint(l.pdf.itemIds,c.pdf.itemIds)){}else continue;if(l.pdf.itemIds.isEmpty()||c.pdf.itemIds.isEmpty())continue;Models.CompareStats st=new Models.CompareStats();List<Models.Occurrence> occ=bestOnly(RasterMatcher.compare(l,c,st));cmp++;\n    trace(new JSONObject().put("event","compare").put("layout",l.pdf.label).put("constructor",c.pdf.label).put("article",c.pdf.article).put("layoutPages",l.pages.size()).put("constructorPages",c.pages.size()).put("candidates",occ.size()).put("bestCoverage",st.bestCoverage).put("bestScore",st.bestScore));\n    for(Models.Occurrence o:occ){o.id=UUID.randomUUID().toString();found.add(o);}update("Сравнение "+cmp+" / "+total,50+cmp*40/total);\n   }'''
b='''   ArrayList<Models.RemotePdf> required=new ArrayList<>(layouts);required.addAll(templates);int i=0;\n   int planned=required.size()+applicationTemplates.size();\n   for(Models.RemotePdf p:required){ensure();update("Скачиваю "+(++i)+" / "+planned+": "+p.label,10+i*25/Math.max(1,planned));download(p);}\n   ArrayList<Models.RemotePdf> applicationOk=new ArrayList<>();\n   JSONArray warnings=root.optJSONArray("warnings");if(warnings==null){warnings=new JSONArray();root.put("warnings",warnings);}\n   for(Models.RemotePdf p:applicationTemplates){ensure();update("Скачиваю "+(++i)+" / "+planned+": "+p.label,10+i*25/Math.max(1,planned));try{download(p);applicationOk.add(p);}catch(Exception ex){String w="Шаблон нанесения "+(p.article==null?"":p.article)+" не загружен: "+ex.getMessage();warnings.put(w);trace(new JSONObject().put("event","application-template-warning").put("article",p.article).put("itemIds",new JSONArray(p.itemIds)).put("message",ex.getMessage()));}}\n   ArrayList<Models.RemotePdf> all=new ArrayList<>(required);all.addAll(applicationOk);\n   ArrayList<Models.PdfIndex> li=new ArrayList<>(),ci=new ArrayList<>(),ai=new ArrayList<>(),refs=new ArrayList<>();\n   int dpi=RasterPdfIndexer.commonDpi(all);trace(new JSONObject().put("event","index").put("dpi",dpi).put("applicationTemplates",applicationOk.size()));\n   for(Models.RemotePdf p:layouts){ensure();li.add(RasterPdfIndexer.index(p,dpi,s->update(s,40)));}\n   for(Models.RemotePdf p:templates){ensure();Models.PdfIndex x=RasterPdfIndexer.index(p,dpi,s->update(s,45));ci.add(x);refs.add(x);}\n   for(Models.RemotePdf p:applicationOk){ensure();Models.PdfIndex x=RasterPdfIndexer.index(p,dpi,s->update(s,48));ai.add(x);refs.add(x);}\n   ArrayList<Models.Occurrence> found=new ArrayList<>();int cmp=0,total=0;\n   for(Models.PdfIndex l:li)for(Models.PdfIndex c:refs)if(sameItem(l.pdf,c.pdf))total++;\n   for(Models.PdfIndex l:li)for(Models.PdfIndex c:refs){ensure();if(!sameItem(l.pdf,c.pdf))continue;Models.CompareStats st=new Models.CompareStats();List<Models.Occurrence> occ=bestOnly(RasterMatcher.compare(l,c,st));cmp++;\n    trace(new JSONObject().put("event","compare").put("layout",l.pdf.label).put("reference",c.pdf.label).put("referenceType",c.pdf.role).put("article",c.pdf.article).put("layoutPages",l.pages.size()).put("referencePages",c.pages.size()).put("candidates",occ.size()).put("bestCoverage",st.bestCoverage).put("bestScore",st.bestScore));\n    for(Models.Occurrence o:occ){o.id=UUID.randomUUID().toString();found.add(o);}update("Сравнение "+cmp+" / "+total,50+cmp*40/Math.max(1,total));\n   }'''
s=rep(s,a,b)
s=rep(s,'.put("indexDpi",dpi).put("comparisons",cmp).put("matches",matches);','.put("indexDpi",dpi).put("comparisons",cmp).put("applicationTemplatesDownloaded",applicationOk.size()).put("matches",matches);')
s=rep(s,'.put("bytes",p.file.length()).put("article",p.article).put("url",p.url)','.put("bytes",p.file.length()).put("article",p.article).put("role",p.role).put("url",p.url)')
s=rep(s,'summary(root,layouts,templates,li,ci,found,dpi)','summary(root,layouts,templates,applicationOk,li,ci,ai,found,dpi)')
# parse function block
st=s.index(' private ArrayList<Models.RemotePdf> parse(');en=s.index(' private void download(',st)
s=s[:st]+''' private ArrayList<Models.RemotePdf> parse(JSONArray arr,String role)throws Exception{\n  if(arr==null)return new ArrayList<>();\n  if(arr.length()>100)throw new IOException("Больше 100 файлов: требуется разделить заказ");LinkedHashMap<String,Models.RemotePdf> out=new LinkedHashMap<>();\n  for(int i=0;i<arr.length();i++){JSONObject o=arr.getJSONObject(i);String url=o.getString("url");Safety.allowed(url,true);String article="layout".equals(role)?null:o.optString("article","");if("null".equals(article))article="";String item=o.optString("item_id","");String label=o.optString("label","file.pdf");if("application".equals(role)){String aa=article==null||article.isEmpty()?"item":article;String id=item.isEmpty()?String.valueOf(i+1):item;label="application_"+aa+"_"+id+".pdf";}String key=url+"|"+article+"|"+role;Models.RemotePdf p=out.get(key);if(p==null){p=new Models.RemotePdf(url,label,article,role);out.put(key,p);}if(!item.isEmpty()&&!item.equals("null"))p.itemIds.add(item);}return new ArrayList<>(out.values());\n }\n private static boolean sameItem(Models.RemotePdf a,Models.RemotePdf b){return !a.itemIds.isEmpty()&&!b.itemIds.isEmpty()&&!Collections.disjoint(a.itemIds,b.itemIds);}\n'''+s[en:]
s=rep(s,'File dir=new File(runDir,p.article==null?"layouts":"constructors");','String folder="layout".equals(p.role)?"layouts":("application".equals(p.role)?"application_templates":"constructors");File dir=new File(runDir,folder);')
s=rep(s,'.put("constructor",o.constructorFile).put("constructorPage",o.constructorPage+1)','.put("constructor",o.constructorFile).put("referenceType",o.referenceType).put("constructorPage",o.constructorPage+1)')
s=rep(s,'private String summary(JSONObject root,List<Models.RemotePdf> l,List<Models.RemotePdf> c,List<Models.PdfIndex> li,List<Models.PdfIndex> ci,List<Models.Occurrence> found,int dpi)throws Exception{','private String summary(JSONObject root,List<Models.RemotePdf> l,List<Models.RemotePdf> c,List<Models.RemotePdf> a,List<Models.PdfIndex> li,List<Models.PdfIndex> ci,List<Models.PdfIndex> ai,List<Models.Occurrence> found,int dpi)throws Exception{')
s=rep(s,'int pages=0;for(Models.PdfIndex p:li)pages+=p.pages.size();for(Models.PdfIndex p:ci)pages+=p.pages.size();StringBuilder s=new StringBuilder("PrintCheck Android "+BuildConfig.VERSION_NAME+"\\nЗаказ №"+requested+"\\n\\nНужна ручная проверка. Это НЕ допуск к печати.\\nТехническая проверка и отделение нанесения ещё не выполнены.\\n\\nPDF-макетов: "+l.size()+" · конструкторов: "+c.size()+"\\nВсего обработано страниц: "+pages+','int pages=0;for(Models.PdfIndex p:li)pages+=p.pages.size();for(Models.PdfIndex p:ci)pages+=p.pages.size();for(Models.PdfIndex p:ai)pages+=p.pages.size();StringBuilder s=new StringBuilder("PrintCheck Android "+BuildConfig.VERSION_NAME+"\\nЗаказ №"+requested+"\\n\\nНужна ручная проверка. Это НЕ допуск к печати.\\nТехническая проверка и отделение нанесения ещё не выполнены.\\n\\nPDF-макетов: "+l.size()+" · конструкторов: "+c.size()+" · шаблонов нанесения: "+a.size()+"\\nВсего обработано страниц: "+pages+')
s=rep(s,'s.append("\\nКонструкторы:\\n");for(Models.RemotePdf p:c)s.append(p.article==null||p.article.isEmpty()?"Артикул не определён":p.article).append(" → ").append(p.label).append(\'\\n\');','s.append("\\nЭталоны:\\n");for(Models.RemotePdf p:c)s.append("[конструктор] ").append(p.article==null||p.article.isEmpty()?"Артикул не определён":p.article).append(" → ").append(p.label).append(\'\\n\');for(Models.RemotePdf p:a)s.append("[шаблон нанесения] ").append(p.article==null||p.article.isEmpty()?"Артикул не определён":p.article).append(" → ").append(p.label).append(\'\\n\');')
s=rep(s,'append(" / ").append(o.constructorFile).append(" · стр. ")','append(" / ").append(o.referenceType).append(" / ").append(o.constructorFile).append(" · стр. ")')
p.write_text(s)
# version increment and UI strings
for p in r.rglob('*'):
 if p.is_file() and p.suffix in {'.java','.xml','.md','.txt','.json','.js','.cjs','.gradle','.kts'}:
  try:s=p.read_text()
  except:continue
  s=s.replace('3.1.0-alpha4','3.1.0-alpha5').replace('versionCode 300006','versionCode 300007')
  p.write_text(s)
print('alpha5 patch applied')
